global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Melista.Services;
global using Melista.ViewModels;
global using Melista.Views;
global using DevExpress.Mvvm;
global using System.Windows.Controls;
global using System;
global using PropertyChanged;
